SELECT *
FROM customer_behavior
LIMIT 20

//1.Total number of revenue generated by male vs female customers?//

SELECT gender,
SUM(purchase_amount) AS revenue
from customer_behavior
GROUP BY gender

#2.Which customer used a discount but still spent more than the average purchase amount?

SELECT customer_id, purchase_amount 
FROM customer_behavior
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_behavior)

# 3. AVERAGE of the purchase_amount

SELECT 
AVG(purchase_amount) AS revenue
FROM customer_behavior;

#4. Which of the top 5 products with the highest average review rating ?

SELECT item_purchased,
ROUND(AVG(review_rating::NUMERIC),2) AS average_rating
FROM customer_behavior
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

#5. Compare the avg purchase amounts between standard and express shipping.

SELECT shipping_type,
ROUND(AVG(purchase_amount::NUMERIC),2) AS avg_purchase_amount
FROM customer_behavior
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type

--6. DO subscribed customers spend more ? compare the avg of spend and total revenue btw subscribers and non subscribers

SELECT subscription_status,
COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount),2) AS avg_spend,
ROUND(SUM(purchase_amount),2) AS avg_revenue
FROM customer_behavior
GROUP BY subscription_status
ORDER BY avg_spend, avg_revenue DESC;

--7.which 5 products have the highest percentage 
of purchases with the discounts applied ?

SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer_behavior
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--8. segement the customers based on their previous purchases into regular, returning and loyal customers 

SELECT cuatom,
ROUND(AVG(purchase_amount::NUMERIC),2) AS avg_purchase_amount
FROM customer_behavior
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type


 